### ISSUE TITLE
Show only note's picture to players

### ISSUE THREAD

**Issue by lucaspicerni** [itamarcu/roll-from-compendium#11]
When sharing a note's image with players, the module allows them to "roll" the image, displaying the note in chat, regardless of the permissions they have on the note.

![image](https://user-images.githubusercontent.com/95550238/161623406-4f4ab5e4-1a4c-41fe-bc0e-4992f15f8b38.png)
![image](https://user-images.githubusercontent.com/95550238/161623535-82108c1e-76a0-4740-b561-017feaacc57c.png)
![image](https://user-images.githubusercontent.com/95550238/161623684-4cb906ab-619a-4bb6-97ad-ce74926d3fc1.png)

**Comment by itamarcu** [comment]
@lucaspicerni - what do you want the module to do instead?

Only show the button if the user's permission for this journal note is Observer or higher?

**Comment by lucaspicerni** [comment]
Yes, please!

**Comment by itamarcu** [comment]
Fixed in v1.3.0
