### ISSUE TITLE
Roll from sheet

### ISSUE THREAD

**Issue by adacosta92** [itamarcu/roll-from-compendium#2]
Is it possible to add the "Roll" button from the "Roll from Compendium" module to the item card once it's opened, at the top, where the "Close" button & the PopOut button (if you have that module) are?

**Comment by adacosta92** [comment]
Also, it'd be totally tight to be able to roll right from the item in the "quick insert" module popup

**Comment by itamarcu** [comment]
Good suggestion!

I'll consider doing it.  In that case, when opening a card from a character sheet, it will roll it with the character's stats no matter which token you have selected.  Yes?

**Comment by adacosta92** [comment]
That may be less necessary, since it can be rolled from the character sheet directly. What would be really good is rolling it with BetterRolls5e integration.

**Comment by itamarcu** [comment]
Yeah, that's what I planned on doing if that module is installed.  But is there a strong use case for it?  Something that you can't already do easily?

**Comment by adacosta92** [comment]
Yeah, I cant imagine someone using dnd5e without it. It's so much better looking.

**Comment by itamarcu** [comment]
Feature is now added in v1.0.0, along with general support for BetterRolls :)
