### ISSUE TITLE
Can't open item sheet with module activated

### ISSUE THREAD

**Issue by adacosta92** [itamarcu/roll-from-compendium#3]
Error: Cannot read property 'constructor' of undefined

I can open item sheets with the module off just fine, and I could open item sheets with previous versions as well

**Comment by itamarcu** [comment]
Whoops!  I released the new version (v1.0.0) with a small bug.  Check the new version (v1.0.1)?

**Comment by itamarcu** [comment]
Wait, actually I might have solved a different bug.  Could you maybe copy-paste or take a screenshot of your debugging console after the error happens (can be opened with F12)?

**Comment by itamarcu** [comment]
(also, try version v1.0.2)

**Comment by itamarcu** [comment]
I think I know the problem - you have libwrapper installed but disabled.  LibWrapper is a requirement module for this one, kinda - if it's not installed the module can work without it, but if it's installed and disabled then apparently there's a bug.

**Comment by itamarcu** [comment]
Fixed in v1.0.3 - it was my fault!

Please reopen this if the fix doesn't work for you!

**Comment by adacosta92** [comment]
It works perfectly now! Thanks!!!

Best,

Ajay

________________________________
