### ISSUE TITLE
Allow to hide "Show in chat" action from journal header

### ISSUE THREAD

**Issue by JJBocanegra** [itamarcu/roll-from-compendium#4]
With so many modules installed there are already too many actions in the header to have another one, which if it can be disabled would do a great favor to those who do not see even the close button :(

**Comment by itamarcu** [comment]
Heh, I knew this day would happen but didn't think it'd be so quickly!

I don't want to pollute the module settings with this, especially not when currently this module has 0 settings.

How about I give you the ability to change the setting through the browser console?

With three states:  Full (showing d20 icon and "Roll"), Partial (showing d20 icon), None (don't show).

**Comment by itamarcu** [comment]
Adding in v1.0.5:

Open the console and run the following command to completely hide the "Roll" / "Show in Chat" button from sheet headers - 

```js
game.settings.set('roll-from-compendium', 'window-header-button', 'Hide')
```

You can run it with several options.

- `Full` (default): will look like "🎲Roll"
- `Only icon`: "🎲"
- `Hide`: Will not add any header button to your sheets.
