### ISSUE TITLE
Option to only show the symbol in the header bar

### ISSUE THREAD

**Issue by fiagewinnt** [itamarcu/roll-from-compendium#6]
I wanted to ask if it would be possible to add an option to only show the symbol in the header bar and not also the text to preserve space? Since I'm running Foundry with a lot of modules that also use the header bar, it got kinda overcrowded now and doesn't show the close button anymore. Only when I resize each window manually every time I open a spell/journal entry etc. to accomodate all the symbols. 

Before resizing:
![image](https://user-images.githubusercontent.com/61601634/111866763-17964a80-8970-11eb-92bd-abf88549cde7.png)

After resizing:
![image](https://user-images.githubusercontent.com/61601634/111866774-27ae2a00-8970-11eb-8aae-29e40b42c632.png)

**Comment by itamarcu** [comment]
In fact, there is!  it was requested in #4 and implemented.

You can look at the issue description there for an explanation on how to change it.

Please close this issue if this resolves your problem.  Also, let me know if you think this is actually something that should appear in the module settings.  I thought to myself that it's a rare requirement, but so far 2 people have already requested this ability..!

**Comment by fiagewinnt** [comment]
Thanks for the quick answer. I'll try that tomorrow. 
If it works from the console I'm fine with it not being an option in a menu. Maybe you could add this solution to the module overview though in case more people are looking for this.
