### ISSUE TITLE
Compatibility with BetterRolls5e (header of item sheets)

### ISSUE THREAD

**Issue by zerodaggerz** [itamarcu/roll-from-compendium#7]
Just wanted to do an FYI that using your built in roll button at the header of item sheets will cause all sheets to have unexpected behavior. Mainly reverting all future edits and requiring a refresh. I'll be posting this to the BetterRolls5e page as well.

**Comment by itamarcu** [comment]
Woah, I didn't notice this myself.  Not sure what we can do about it... but thanks a lot for reporting this and for posting in the other module too!

**Comment by itamarcu** [comment]
I can't reproduce this.  @zerodaggerz can you reproduce this with the newest version (v1.3.0)?  if so, please reopen the bug.
